"""empty message

Revision ID: 1f48ed715443
Revises: 760b3d2b5caf
Create Date: 2020-09-02 12:09:19.452112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f48ed715443'
down_revision = '760b3d2b5caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('l_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'l_access')
    # ### end Alembic commands ###
