"""empty message

Revision ID: 2855d7e09a1f
Revises: 8e1300d6743e
Create Date: 2020-09-06 17:23:28.544361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2855d7e09a1f'
down_revision = '8e1300d6743e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('module', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'position')
    op.drop_column('level', 'position')
    # ### end Alembic commands ###
