"""empty message

Revision ID: 35c5834ba01a
Revises: 
Create Date: 2020-08-29 19:14:51.101474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c5834ba01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.Column('worksheet_url', sa.Unicode(), nullable=True),
    sa.Column('video_url', sa.Unicode(), nullable=True),
    sa.Column('worksheet_answers_url', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('lplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('amount', sa.Unicode(), nullable=True),
    sa.Column('period', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('amount', sa.Unicode(), nullable=True),
    sa.Column('period', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('ps_code', sa.String(), nullable=True),
    sa.Column('ps_email', sa.Unicode(), nullable=True),
    sa.Column('lesson_progress', sa.Unicode(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('email', sa.Unicode(length=123), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.Unicode(length=123), nullable=True),
    sa.Column('last_name', sa.Unicode(length=123), nullable=True),
    sa.Column('password_hash', sa.String(length=123), nullable=True),
    sa.Column('description', sa.Unicode(length=123), nullable=True),
    sa.Column('about', sa.UnicodeText(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('show_email', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=347), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('authorization_code', sa.Unicode(), nullable=True),
    sa.Column('card_type', sa.Unicode(), nullable=True),
    sa.Column('last4', sa.Unicode(), nullable=True),
    sa.Column('exp_month', sa.Unicode(), nullable=True),
    sa.Column('exp_year', sa.Unicode(), nullable=True),
    sa.Column('bin', sa.Unicode(), nullable=True),
    sa.Column('bank', sa.Unicode(), nullable=True),
    sa.Column('signature', sa.Unicode(), nullable=True),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_level',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'level_id')
    )
    op.create_table('lesson_module',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'module_id')
    )
    op.create_table('lesson_subject',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'subject_id')
    )
    op.create_table('lesson_year',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'year_id')
    )
    op.create_table('user_lplans',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lplan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lplan_id'], ['lplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lplans')
    op.drop_table('lesson_year')
    op.drop_table('lesson_subject')
    op.drop_table('lesson_module')
    op.drop_table('lesson_level')
    op.drop_table('card')
    op.drop_table('year')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('module')
    op.drop_table('m_plan')
    op.drop_table('lplan')
    op.drop_table('level')
    op.drop_table('lesson')
    # ### end Alembic commands ###
