"""empty message

Revision ID: 5b1defcd29c6
Revises: 7bab826cf489
Create Date: 2020-09-04 14:20:54.006930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1defcd29c6'
down_revision = '7bab826cf489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('l_plan_services',
    sa.Column('l_plan_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['l_plan_id'], ['l_plan.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.create_table('user_l_plans',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('l_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['l_plan_id'], ['l_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_plans')
    op.drop_table('plan')
    op.drop_table('plan_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_services',
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.create_table('plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ps_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('period', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plans',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_l_plans')
    op.drop_table('l_plan_services')
    op.drop_table('l_plan')
    # ### end Alembic commands ###
