"""empty message

Revision ID: 8e1300d6743e
Revises: 5b1defcd29c6
Create Date: 2020-09-05 14:01:08.434348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1300d6743e'
down_revision = '5b1defcd29c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('l_plan', sa.Column('year', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('l_plan', 'year')
    # ### end Alembic commands ###
