"""empty message

Revision ID: 8f3b417b5036
Revises: 2855d7e09a1f
Create Date: 2020-09-06 17:24:34.879366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3b417b5036'
down_revision = '2855d7e09a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'position')
    op.drop_column('module', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('position', sa.INTEGER(), nullable=True))
    op.add_column('level', sa.Column('position', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
