"""empty message

Revision ID: 9519a1d78105
Revises: b43465cad491
Create Date: 2020-08-28 07:07:27.016921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9519a1d78105'
down_revision = 'b43465cad491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('authorization_code', sa.Unicode(), nullable=True),
    sa.Column('card_type', sa.Unicode(), nullable=True),
    sa.Column('last4', sa.Unicode(), nullable=True),
    sa.Column('exp_month', sa.Unicode(), nullable=True),
    sa.Column('exp_year', sa.Unicode(), nullable=True),
    sa.Column('bin', sa.Unicode(), nullable=True),
    sa.Column('bank', sa.Unicode(), nullable=True),
    sa.Column('signature', sa.Unicode(), nullable=True),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('ps_email', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ps_email')
    op.drop_table('card')
    # ### end Alembic commands ###
