"""empty message

Revision ID: b43465cad491
Revises: 
Create Date: 2020-08-27 16:24:34.989850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43465cad491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('amount', sa.Unicode(), nullable=True),
    sa.Column('period', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.Column('ps_code', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('email', sa.Unicode(length=123), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.Unicode(length=123), nullable=True),
    sa.Column('last_name', sa.Unicode(length=123), nullable=True),
    sa.Column('password_hash', sa.String(length=123), nullable=True),
    sa.Column('description', sa.Unicode(length=123), nullable=True),
    sa.Column('about', sa.UnicodeText(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('show_email', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=347), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_table('plan')
    # ### end Alembic commands ###
