"""empty message

Revision ID: e6128074c4bf
Revises: fc730c0b9a45
Create Date: 2020-09-08 00:05:28.964605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6128074c4bf'
down_revision = 'fc730c0b9a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year', 'year')
    # ### end Alembic commands ###
